### ISSUE TITLE
Fix deployment of generated pages with github pages 

### ISSUE THREAD

**Issue by Doreapp** [Doreapp/Doreapp.github.io#6]
Currently, the pages are deployed but the index is the README and not the generated index.html as expected since #4

**Comment by Doreapp** [comment]
According to some research, github native build of jekyll websites doesn't accept every plug-ins. Thus, we need to build the pages locally and the deploy it.

References:
- https://github.com/avillafiorita/jekyll-datapage_gen/issues/28
- https://jekyllrb.com/docs/plugins/installation/

**Comment by Doreapp** [comment]
This may be a solution:

```yaml
# .github/workflows/github-pages.yml
name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@2.0.5    # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
```

Found [here](https://jekyllrb.com/docs/continuous-integration/github-actions/)
